//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БИПиТ10
{
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [Display(Name = "Id заказа")]
        public int IdO { get; set; }
        [Display(Name = "Клиент")]
        public int IdC_FK { get; set; }
        [Display(Name = "Услуга")]
        public int IdS_FK { get; set; }
        [Display(Name = "Срок")]
        public int Time { get; set; }
        [Display(Name = "Дата заказа")]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]
        public System.DateTime Date { get; set; }

        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
